steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-flask-app', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/my-flask-app']
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'run', 'deploy', 'my-flask-app',
    '--image', 'gcr.io/$PROJECT_ID/my-flask-app',
    '--region', 'us-central1',
    '--platform', 'managed',
    '--allow-unauthenticated',
    '--set-env-vars', 'FLASK_APP=app.py,FLASK_ENV=production'
  ]
images:
- 'gcr.io/$PROJECT_ID/my-flask-app'
